# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 11:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0002_wal'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_tr_usr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_chg_usr', models.DateTimeField(default='ops')),
                ('last_chg_dt', models.DateTimeField(auto_now=True)),
                ('highlighted', models.TextField()),
            ],
            options={
                'ordering': ('wallet_id',),
            },
        ),
        migrations.CreateModel(
            name='tr_status_map',
            fields=[
                ('map_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=25, null=True)),
                ('last_chg_usr', models.DateTimeField(default='ops')),
                ('last_chg_dt', models.DateTimeField(auto_now=True)),
                ('highlighted', models.TextField()),
            ],
            options={
                'ordering': ('map_id',),
            },
        ),
        migrations.CreateModel(
            name='transaction_failed',
            fields=[
                ('tr_fld_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('last_chg_usr', models.DateTimeField(default='ops')),
                ('last_chg_dt', models.DateTimeField(auto_now=True)),
                ('highlighted', models.TextField()),
            ],
            options={
                'ordering': ('tr_fld_id', 'tr_id'),
            },
        ),
        migrations.CreateModel(
            name='transaction_stats',
            fields=[
                ('tr_st_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('last_chg_usr', models.DateTimeField(default='ops')),
                ('last_chg_dt', models.DateTimeField(auto_now=True)),
                ('highlighted', models.TextField()),
            ],
            options={
                'ordering': ('tr_st_id',),
            },
        ),
        migrations.CreateModel(
            name='transaction_top_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('last_chg_usr', models.DateTimeField(default='ops')),
                ('last_chg_dt', models.DateTimeField(auto_now=True)),
                ('highlighted', models.TextField()),
            ],
            options={
                'ordering': ('tr_id', 'tot_id'),
            },
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('tr_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('last_chg_usr', models.DateTimeField(default='ops')),
                ('last_chg_dt', models.DateTimeField(auto_now=True)),
                ('highlighted', models.TextField()),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.tr_status_map')),
            ],
            options={
                'ordering': ('tr_id', 'tot_id'),
            },
        ),
        migrations.CreateModel(
            name='type_of_tr',
            fields=[
                ('tot_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('short_desc', models.CharField(max_length=10)),
                ('full_desc', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=200)),
                ('last_chg_usr', models.DateTimeField(default='ops')),
                ('last_chg_dt', models.DateTimeField(auto_now=True)),
                ('highlighted', models.TextField()),
            ],
            options={
                'ordering': ('tot_id', 'short_desc', 'full_desc', 'format'),
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(editable=False, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="User Name must the alphanumeric and only ('.', '-') are allowed as an special character ", regex='^[a-zA-Z0-9_.-]+$')])),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('facebook_id', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_dt', models.DateTimeField()),
                ('last_chg_usr', models.DateTimeField(default='ops')),
                ('last_chg_dt', models.DateTimeField(auto_now=True)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_name', 'name', 'email_id'),
            },
        ),
        migrations.CreateModel(
            name='user_wallet',
            fields=[
                ('wallet_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('money', models.FloatField()),
                ('loyalty_points', models.FloatField()),
                ('last_chg_usr', models.DateTimeField(default='ops')),
                ('last_chg_dt', models.DateTimeField(auto_now=True)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.user')),
            ],
            options={
                'ordering': ('wallet_id', 'user_id', 'money', 'loyalty_points'),
            },
        ),
        migrations.AddField(
            model_name='type_of_tr',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_tr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactions',
            name='tot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.type_of_tr'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.user_wallet'),
        ),
        migrations.AddField(
            model_name='transaction_top_10',
            name='tot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.type_of_tr'),
        ),
        migrations.AddField(
            model_name='transaction_top_10',
            name='tr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.transactions'),
        ),
        migrations.AddField(
            model_name='transaction_top_10',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.user_wallet'),
        ),
        migrations.AddField(
            model_name='transaction_stats',
            name='tr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.transactions'),
        ),
        migrations.AddField(
            model_name='transaction_failed',
            name='tr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.transactions'),
        ),
        migrations.AddField(
            model_name='active_tr_usr',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_tr_usr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='active_tr_usr',
            name='tr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.transactions'),
        ),
        migrations.AddField(
            model_name='active_tr_usr',
            name='tr_st_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.transaction_stats'),
        ),
        migrations.AddField(
            model_name='active_tr_usr',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.user_wallet'),
        ),
    ]
